### ISSUE TITLE
Forbidden redirect

### ISSUE THREAD

**Issue by k-topolyan** [jhu-ep-coursera/capstone_demoapp#10]
I noticed that now the JHU server redirects from http to https URL/protocol.

Looks like a good thing, but when running the rakefile, images are downloading from it, so it should cause error like "rake aborted, redirection forbidden".

Fixed by simply changing `BASE_URL="http://dev9.jhuep.com/fullstack-capstone"` to  `BASE_URL="https://dev9.jhuep.com/fullstack-capstone"`.

I can add this to my pull request.

**Comment by k-topolyan** [comment]
Also, `image_content_helper.rb` uses this URL too, so I would fix it as well, to avoid a possible error.

**Comment by ejavaguy** [comment]
Right. Found out about that this weekend and addressing that. I should be
posting that with other corrections soon. This required a change in the
rakefile and rspec

Thanks

**Comment by ejavaguy** [comment]
URL has been corrected
