### ISSUE TITLE
UI/frontend improvements 

### ISSUE THREAD

**Issue by k-topolyan** [jhu-ep-coursera/capstone_demoapp#4]
Hello, Jim. I have some minor fixes/improvements on the client side (besides minor styling additions that I will not mention).

The Things page contains Image-viewer, but when the page doesn't contain images, the switches looks a little superfluous, isn't it?
![image-viewer](https://cloud.githubusercontent.com/assets/10576847/25406676/3804c170-2a10-11e7-9138-4410dcdb912c.png)
![image-viewer-2](https://cloud.githubusercontent.com/assets/10576847/25406749/794721e6-2a10-11e7-9296-3c32d71b139b.png)

This can be fixed by adding _ng-show="$ctrl.images"_ to them:
```
<span class="overlay glyphicon glyphicon-chevron-left"
        ng-click="$ctrl.previousImage()" ng-show="$ctrl.images"></span>

  <span class="overlay glyphicon glyphicon-chevron-right"
        ng-click="$ctrl.nextImage()" ng-show="$ctrl.images"></span> 
```
(/app/assets/javascripts/spa-demo/layout/image_viewer/image_viewer.html)

Thus, we see them only where we actually have images. Looks better, huh?

It's not particularly critical, but maybe you could fix it in your example if you want. I have a few more minor fixes, I can add them here if you think this is useful.

**Comment by ejavaguy** [comment]
> I have a few more minor fixes, I can add them here if you think this is useful.
Sure -- although the pages of the example are not meant to be perfect, these are the type of issues I would have corrected had I noticed them. Yes -- post a separate issue for each item you find and have time to report. I will address them over time.

**Comment by k-topolyan** [comment]
Some time has passed. Just wondering, didn't you forgot?

**Comment by ejavaguy** [comment]
No. I agree that I would have fixed them as a part of developing the original source code baseline tags. However, they are not at the severity level to bump other priorities. Students can use your issue reports to alert them of the error and feel free to fix within their own baseline. If you want to submit a pull request off the master branch with a fix that
a) has a unit test that identifies the problem
b) fixes the problem so that the unit test is successful
I would gladly add those changes after the final course tag.

Thanks again for pointing out the issues. I really appreciate it.

**Comment by k-topolyan** [comment]
Sounds like a good idea, but I'm not sure that we really need a unit test, because these changes mostly related to styles and don't affect other functionality.

"[CSS fix](https://github.com/jhu-ep-coursera/capstone_demoapp/issues/5)" fixes only margins.

In Capybara we can look for CSS selector by `expect(page).to have_css`, so we need to add a separate selector, say, "navbar-form-m0" instead of the existing one.
It could be tested like:
```
  describe "Navbar" do
    it "has 0 margins" do
      visit "/"
      expect(page).to have_css(".navbar-form-m0")
    end
  end 
```
But I don't think that it makes much sense. We don't test every our style, right?

In the fix above, about **Image-viewer**, we are adding `ng-show="$ctrl.images"`, so we don't see the switches in an unnecessary place (on the Things page), but we see them wherever we need.

We can test it like:
```
  describe "Image viewer" do
    it "hides swithers" do
      visit "#{ui_path}/#/things/"
      expect(page).to have_css("sd-image-viewer .glyphicon-chevron-left",:visible=>false)
      expect(page).to have_css("sd-image-viewer .glyphicon-chevron-right",:visible=>false)
    end
  end
```
It makes a little more sense than the previous test.

"[AngularJS improvements](https://github.com/jhu-ep-coursera/capstone_demoapp/issues/6)" touches the Things page and Sign Up page — it's two improvements.

I'll start with **Things**.

It's quite easy to check the text on the page (although I'm not sure if I would do this on a real project, haha):
```
  describe "Things" do
    it "displays text" do
      visit "#{ui_path}/#/things/"
      expect(page).to have_content("Log in to see the list of things. It is visible only to members of things (certain users).")
    end
```
Would be useful to check if we don't have it on nested pages:
```
    it "not displays on sole" do
      visit "#{ui_path}/#/things/1"
      expect(page).to have_no_content("Log in to see the list of things. It is visible only to members of things (certain users).")
    end
  end
```

But it seems a bit more difficult for me to check whether **logged** user sees this. Of course I know that he doesn't see, haha, but I need to write this properly in the spec.

As for the **Sign Up page**, here, too, I need to think a little, maybe we could include this test right into _authns_spec_.

But is this really so important?

In general, this is my thoughts. I could provide a pool request without a test in no time, but if you still think that it is needed, I will have to think a little more.

**Comment by k-topolyan** [comment]
I just wrote a full test, so I can submit a pull request (with the test) soon.

**Comment by ejavaguy** [comment]
> I'm not sure that we really need a unit test, because these changes mostly related to styles and don't affect other functionality.
Somewhat true statement in general, but this is a course -- not a production with schedule/costs. Try to push yourself to see what you can come with to verify, but yes -- the functional tests (i.e., can see, cannot see) make more sense than pure visual (e.g., too far left/right).

There were too many unrelated issues discussed in this one thread to specifically comment on. Please keep the testing/implementation of each reported issue within its own thread.

> But is this really so important? 
Again -- this is a course and in this course testing was very important. Try to push yourself to see how you can automate the proof of an issue and its correction to be able to apply it in other areas down the road.

> In general, this is my thoughts. I could provide a pool request without a test in no time, but if you still think that it is needed, I will have to think a little more.

This is not a race at this point. Aim for quality and completeness in what gets modified. I make the above statement all of the time at work ("I can fix it in a few minutes, but will need the better part of the day to write the automated tests to verify"). However, I know that without the automated tests and pile on 100s of these issues, the change could get accidentally lost/broken with changes down the road.

Thanks.

**Comment by ejavaguy** [comment]
corrections for image viewer and account signup addressed by pull request
