### ISSUE TITLE
CSS fix

### ISSUE THREAD

**Issue by k-topolyan** [jhu-ep-coursera/capstone_demoapp#5]
This is small CSS issue.

When you have an address entered, and the size of your window is less than a certain point, there is problem with margins:
![margins](https://cloud.githubusercontent.com/assets/10576847/25429140/b0dd4728-2a80-11e7-8037-11a64a579a9a.png)

This is comes from Bootstrap:
```
    margin-right: -15px;
    margin-left: -15px;
```
Fixed by adding:
```
.navbar-form {
  margin-left: 0px;
  margin-right: 0px;
}
```

![margins2](https://cloud.githubusercontent.com/assets/10576847/25429355/63032ce2-2a81-11e7-8144-ee5f3752fb62.png)

Looks much better, huh?

**Comment by ejavaguy** [comment]
css changes addressed by pull request
