### ISSUE TITLE
AngularJS improvements

### ISSUE THREAD

**Issue by k-topolyan** [jhu-ep-coursera/capstone_demoapp#6]
Unlike previous issues, this is more like an improvement or a small extension.

Signup page is good thing for sure. But when you are registered and navigate to #/signup route again, this form is still showing up.

I've added `ng-show="!$ctrl.getCurrentUser()"` to this form, and `<p ng-if="$ctrl.getCurrentUser()">It seems you are already logged in!</p>` below.

Of course, we should not forget to add `vm.getCurrentUser = Authn.getCurrentUser;` to signup.component.js.

So now this page corresponds dependent to user logged in or not:
![signup](https://cloud.githubusercontent.com/assets/10576847/25430756/8a9e7842-2a86-11e7-97be-f7868844bd6e.png)
![signup2](https://cloud.githubusercontent.com/assets/10576847/25430759/90938e9a-2a86-11e7-8675-7bb2168c658e.png)

Another thing that I would add, it's short notification on the Things page.
Only if you are not logged in, you get this message:
![things](https://cloud.githubusercontent.com/assets/10576847/25430841/e9d9dd38-2a86-11e7-8e6a-98896e1626d0.png)

At beginning of the thing_selector:
`<p class="thing-list" ng-if="$ctrl.items" ng-hide="$ctrl.authz.canQuery">Log in to see the list of things. It is visible only to members of things (certain users).</p>`
_ng-if="$ctrl.items"_  and _ng-hide="$ctrl.authz.canQuery"_ have some freedom of combination. CSS class is optional, of course.

If we didn't had ng-if="$ctrl.items", this message would show up on the bottom of every single thing too.

Looks good too, right? You may to not add these two features to your example, but I thought it would be useful to show.

**Comment by ejavaguy** [comment]
Account signup accepted from pull request but additional text added to Things display was not since it was "not in error". Let's keep some consistency with the course videos and keep changes to errors.
